[package]
name = "skip-if-macros"
description.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.20.9"
quote = "1.0.36"
syn = "2.0.66"
