[package]
name = "skip-if-macros"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.20.9"
log = "0.4.21"
quote = "1.0.36"
syn = "2.0.66"
